### ISSUE TITLE
ADD_POKEMON_BUILD & USER_PROFILE -> problema con diccionarios

### ISSUE THREAD

**Issue by kraskarocio** [Villanueva-Flavio/TP_IDS_Pokebuild-Maker#24]
Si el usuario tiene **un solo pokemon** y vas a */add_build_form/<user_id>* te va a aparecer el siguiente error:
![imagen](https://github.com/Villanueva-Flavio/TP_IDS_Pokebuild-Maker/assets/150710084/a86abe79-c311-42c7-9997-47355bf0f872)
El mismo error sucede si vas a */user_profile/<user_id>*, si el usuario tiene **una sola build**, te aparece el mismo error.

**Comment by SrMaximiliano** [comment]
Lo pude arreglar, era usar 
      if isinstance(user_pokemons, dict):
        user_pokemons = [user_pokemons]
  Porque cuando solo hay un pokemon, en vez de devolver una lista con solo el diccionario del Pokémon, devuelve solo el diccionario, lo que genera un error con el for

**Comment by kraskarocio** [comment]
este usuario tiene 1 build y me sigue apareciendo el error. USER ID 20
![modify_build](https://github.com/Villanueva-Flavio/TP_IDS_Pokebuild-Maker/assets/150710084/ffa5e9f2-0d1f-4137-b145-e5be162e1434)
el usuario 13 tiene un solo pokemon y me aparece el mismo error

**Comment by SrMaximiliano** [comment]
se arreglaba haciendole un if isinstance para cada caso donde se usaba un build, pokemon o lo que sea
