### ISSUE TITLE
Hay pokemones que no me deja eliminar. 

### ISSUE THREAD

**Issue by kraskarocio** [Villanueva-Flavio/TP_IDS_Pokebuild-Maker#27]
![deletepok](https://github.com/Villanueva-Flavio/TP_IDS_Pokebuild-Maker/assets/150710084/c0fede89-f4c6-474d-b5a7-9887660984f4)
Como se ve, hay pokemones que me deja borrar y otros que no. Me fijé en el postman y de casualidad esos pokemones son los primeros de alguna build del usuario. Como sabemos, el pokemon_id_1 en NOT NULL.
**posible solución:** Luego de eliminar un elemento, reordenar la build, tal que el ultimo pokemon que quede sea el primero, (no sé si implementamos eso todavía lvdd) y luego, cuando se elemine el primero, se elimina la build

**Comment by SrMaximiliano** [comment]
Estoy casi seguro que se arreglo con el error previo de isinstance(). Porque ese error arreglaba los casos donde solo habia 1 unica build o pokemon y desde entonces no tengo este error.
